spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: safepassword
  ai:
    vectorstore:
      neo4j:
        label: Document
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.3
      embedding:
        options:
          model: text-embedding-ada-002

carina:
  vectorSearch:
    topK: 4
    similarityThreshold: 0.75